apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: local.com/nfs
allowVolumeExpansion: true
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-path
      volumes:
      - name: nfs-path
        hostPath:
          path: /home/go/kubernetes-storage/nfs
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  # see https://github.com/kubernetes/minikube/issues/3417
  type: ClusterIP
  clusterIP: 10.96.0.50
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
