apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: ip-space
      protocol: layer2
      addresses:
      - 5.45.108.1-5.45.111.254
